### ISSUE TITLE
%ni% ca be confusing

### ISSUE THREAD

**Issue by stla** [BenWiseman/roperators#1]
Hello,

  Thank you for this great package.

  I find `%ni%` can be confusing. In LaTeX, `$\in$` is the symbol "belongs to" and `$\ni$` is the reversed symbol. So `a %ni% b` can be interpreted as ` b %in% a`. I personally use `%notin%` in my packages (that I wrote myself).

**Comment by BenWiseman** [comment]
I certainly understand your preference, however changing the API to accommodate that will break reverse dependencies which is a problem for existing users and in violation of CRAN update policies. 

If others have the same issue, I can add an alias. I'm going to close this from being an issue as it's not really a bug.
